### ISSUE TITLE
Dataset at ftp:/podaac.jpl.nasa.gov/allData/ghrsst

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#204] opened 2017-01-25 07:17 UTC
ftp:/podaac.jpl.nasa.gov/allData/ghrsst.

Suggested in a large email containing many urls

**Comment by gabefair** [comment] 2017-01-25 16:45
Downloading now

**Comment by bkirkbri** [comment] 2017-01-31 23:19
Appears to be a duplicate of #192. @gabefair Were you able to mirror this one?

**Comment by bkirkbri** [comment] 2017-02-15 21:28
Closing as a duplicate of #241. Please comment there instead of here.

**Closed by bkirkbri** 2017-02-15 21:28 UTC
Labels: NASA, No Mirrors, PODAAC
