### ISSUE TITLE
NASA PODAAC Coastal Sea Surface Height and Currents Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#240] opened 2017-01-25 07:20 UTC
ftp:/podaac-ftp.jpl.nasa.gov/allData/coastal_alt.

Suggested in a large email containing many urls

**Comment by Proplex** [comment] 2017-01-26 22:34
Downloading

**Comment by nubenum** [comment] 2017-01-30 17:44
Duplicate of #190

**Comment by bkirkbri** [comment] 2017-01-30 20:25
@Proplex Were you able to complete a mirror of this data? Thanks!

**Comment by donbright** [comment] 2017-02-04 00:42
agree with @nubenum, this is dup of #190 

Size estimate: 3T

**Comment by gabefair** [comment] 2017-02-09 04:05
1 vote to close

**Comment by bkirkbri** [comment] 2017-02-15 21:30
Closing as a duplicate of #190 - comment there with any updates.

**Closed by bkirkbri** 2017-02-15 21:30 UTC
Labels: In Progress, NASA, No Mirrors, Size Estimated
