### ISSUE TITLE
Dataset at ftp:/ladsftp.nascom.nasa.gov/README

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#179] opened 2017-01-25 07:15 UTC
ftp:/ladsftp.nascom.nasa.gov/README.

Suggested in a large email containing many urls

**Comment by as-com** [comment] 2017-01-25 22:41
duplicate of https://github.com/climate-mirror/datasets/issues/180

**Comment by mxplusb** [comment] 2017-01-25 22:43
duplicate of #178

**Closed by mxplusb** 2017-01-25 22:43 UTC
