### ISSUE TITLE
Dataset at ftp:/podaac-ftp.jpl.nasa.gov/allData/grace

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#243] opened 2017-01-25 07:20 UTC
ftp:/podaac-ftp.jpl.nasa.gov/allData/grace.

Suggested in a large email containing many urls

**Comment by mxplusb** [comment] 2017-01-25 21:40
duplicate of #261

**Closed by mxplusb** 2017-01-25 21:40 UTC
Labels: No Mirrors
