### ISSUE TITLE
Dataset at ftp:/ladsweb.nascom.nasa.gov/../allData

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#180] opened 2017-01-25 07:15 UTC
ftp:/ladsweb.nascom.nasa.gov/../allData.

Suggested in a large email containing many urls

**Comment by as-com** [comment] 2017-01-25 22:41
Might be duplicate of https://github.com/climate-mirror/datasets/issues/178

**Comment by mxplusb** [comment] 2017-01-25 22:42
Looks like it, thanks!

**Closed by mxplusb** 2017-01-25 22:42 UTC
Labels: No Mirrors
