### ISSUE TITLE
NASA NESDIS Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#223] opened 2017-01-25 07:19 UTC
ftp:/www.star.nesdis.noaa.gov/pub/sod.

Suggested in a large email containing many urls

**Comment by as-com** [comment] 2017-01-25 22:29
"Connection refused"

**Comment by mxplusb** [comment] 2017-01-25 22:40
Yeah, same here.

@nickrsan can you ask for a better link from the link provider? thanks.

**Comment by infernix** [comment] 2017-01-27 17:46
It's ftp://ftp.star.nesdis.noaa.gov/pub/sod/ but the dataset is huge, i stopped counting at 20TB.

**Comment by infernix** [comment] 2017-01-27 20:10
This is actualy a dupe of #166

**Comment by bkirkbri** [comment] 2017-01-31 04:27
Closing as a duplicate.

**Closed by bkirkbri** 2017-01-31 04:27 UTC
Labels: NASA, NESDIS, No Mirrors
