### ISSUE TITLE
Dataset at ftp:/podaac-ftp.jpl.nasa.gov/allData/quikscat

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#253] opened 2017-01-25 07:21 UTC
ftp:/podaac-ftp.jpl.nasa.gov/allData/quikscat.

Suggested in a large email containing many urls

**Comment by mxplusb** [comment] 2017-01-25 21:36
duplicate of #265

**Closed by mxplusb** 2017-01-25 21:36 UTC
Labels: NASA, No Mirrors, PODAAC
