### ISSUE TITLE
Dataset at http:/ftpbrowser.gsfc.nasa.gov/ae_de2_s.html

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#227] opened 2017-01-25 07:19 UTC
http:/ftpbrowser.gsfc.nasa.gov/ae_de2_s.html.

Suggested in a large email containing many urls

**Comment by mxplusb** [comment] 2017-01-25 22:30
duplicate of #229

**Closed by mxplusb** 2017-01-25 22:30 UTC
Labels: No Mirrors
