### ISSUE TITLE
Dataset at http:/ftpbrowser.gsfc.nasa.gov/magsat.html

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#228] opened 2017-01-25 07:19 UTC
http:/ftpbrowser.gsfc.nasa.gov/magsat.html.

Suggested in a large email containing many urls

**Comment by mxplusb** [comment] 2017-01-25 22:29
duplicate of #229

**Closed by mxplusb** 2017-01-25 22:29 UTC
Labels: No Mirrors
