### ISSUE TITLE
Dataset at ftp:/amrc.ssec.wisc.edu

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#140] opened 2017-01-25 07:12 UTC
ftp:/amrc.ssec.wisc.edu.

Suggested in a large email containing many urls

**Comment by claughinghouse** [comment] 2017-01-26 15:18
Downloading.

**Comment by donbright** [comment] 2017-01-27 23:03
this appears to be a duplicate of #139 (same url)

**Closed** 2017-03-07 20:00 UTC
Labels: Low Priority, No Mirrors
