### ISSUE TITLE
NASA PODAAC Salinity Processes in the Upper Ocean Regional Study Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#244] opened 2017-01-25 07:20 UTC
ftp:/podaac-ftp.jpl.nasa.gov/allData/insitu.

Suggested in a large email containing many urls

**Comment by adinbied** [comment] 2017-01-25 23:12
I'll start in on this one!

**Comment by adinbied** [comment] 2017-01-25 23:35
Alright, got it done and am uploading it to a mirror now.

**Comment by adinbied** [comment] 2017-01-26 01:50
Dataset Homepage: [ftp://podaac-ftp.jpl.nasa.gov/allData/insitu](ftp://podaac-ftp.jpl.nasa.gov/allData/insitu)
Mirror URLs:  [https://archive.org/details/NASAPODAACSalinityProcessesInTheUpperOceanRegionalStudyData](https://archive.org/details/NASAPODAACSalinityProcessesInTheUpperOceanRegionalStudyData)
Mirrored By: adinbied
Size: 1.61 GB
Responsible Agency: NASA

**Comment by bkirkbri** [comment] 2017-01-31 04:29
Duplicate of #193.

**Closed** 2017-01-31 04:45 UTC
Labels: NASA, No Mirrors, PODAAC
