### ISSUE TITLE
Dataset at ftp:/podaac.jpl.nasa.gov/allData/saral

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#208] opened 2017-01-25 07:17 UTC
ftp:/podaac.jpl.nasa.gov/allData/saral.

Suggested in a large email containing many urls

**Comment by wsh** [comment] 2017-01-28 01:27
Downloading.

**Comment by donbright** [comment] 2017-01-30 04:51
probable duplicate of #200 and #256

**Comment by wsh** [comment] 2017-01-30 20:46
Downloaded. Investigating hosting options.

**Comment by bkirkbri** [comment] 2017-01-30 22:23
@wsh Thanks! Can you post `find podaac.jpl.nasa.gov/allData/saral -type f -exec md5sum {} \; | grep -v \\.listing | md5sum` to help with cross mirror verification?

**Comment by bkirkbri** [comment] 2017-01-30 22:23
Duplicate of #256

**Comment by wsh** [comment] 2017-02-01 03:21
```ad38720321c16855fa93c67cd744ca7d```

**Comment by gabefair** [comment] 2017-02-09 03:58
@wsh , if your copy is still good, can you please comment over at ticket #256, as we will be closing this ticket as its a duplicate.

**Comment by bkirkbri** [comment] 2017-02-09 21:07
Closing as a duplicate

**Closed by bkirkbri** 2017-02-09 21:07 UTC
Labels: Private Mirror, Single Mirror
