### ISSUE TITLE
ftp://podaac-ftp.jpl.nasa.gov/allData/goes/

### ISSUE THREAD

**Issue by JeremiahCurtis** [climate-mirror/datasets#290] opened 2017-01-29 01:47 UTC
# SEE #242 INSTEAD

ftp://podaac-ftp.jpl.nasa.gov/allData/goes/

**Comment by ivanstegic** [comment] 2017-01-29 02:02
Working on this...

**Comment by gabefair** [comment] 2017-01-31 02:02
@ivanstegic  hows it going?

**Comment by bkirkbri** [comment] 2017-01-31 23:14
Duplicate of #242.

@ivanstegic Can you please post any status updates in #242? Thank you.

**Comment by jradzuweit** [comment] 2017-02-05 23:58
Started creating mirror on "ftp://78.47.40.59/mirrors"

**Comment by gabefair** [comment] 2017-02-09 04:04
1 vote to close

**Comment by jradzuweit** [comment] 2017-02-10 22:14
ftp@sirius:~/mirrors/podaac-ftp.jpl.nasa.gov/allData/goes> lftp -c "open ftp://podaac-ftp.jpl.nasa.gov/allData/goes/ &&du -h -d1" 
1.8T    ./L3                                                                                            
4.0G    ./retired                                                                                            
1.8T    .
Started to mirror this at ftp://176.9.40.3/mirror_b, will update here when finished.

**Comment by ivanstegic** [comment] 2017-02-13 20:35
Happy to report that the full FTP site of 1.8TB is now available on the Our Data Our Hands server and will remain there permanently. You can save this in your bookmarks: http://data.ourdataourhands.org/podaac-ftp.jpl.nasa.gov/

We're working to get as much data mirrored on our servers (and soon global grid!) as possible.


+1 vote to close this issue.

**Comment by ivanstegic** [comment] 2017-02-13 20:36
Actually, I just saw that I'm missing about 300GB, it's currently synchronizing, and should be available by tomorrow morning on the same URL. Don't close just yet.

**Comment by ivanstegic** [comment] 2017-02-14 19:41
I have 1.5TB and it's live now at http://data.ourdataourhands.org/podaac-ftp.jpl.nasa.gov/

**Comment by bkirkbri** [comment] 2017-02-15 20:43
@jradzuweit Did you get a complete mirror of this one?

**Comment by jradzuweit** [comment] 2017-02-15 21:44
still running, looks like that the server has reduced its transfer speed

**Comment by gabefair** [comment] 2017-03-04 14:42
@jradzuweit Thank you for downloading, Please let us know when its done at #242 . We are closing this ticket now.

**Closed** 2017-03-04 14:43 UTC
